apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  project
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: project
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: project
        image: mlopsprojectregistry.azurecr.io/random-forest-api:tag
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: project
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: project
